language: go

go:
  - 1.6
  - 1.5.3
  - 1.5.2
  - 1.5.1
  - 1.5
  - 1.4.3
  - 1.4.2
  - 1.4.1
  - 1.4
  - tip
  - 1.3.3
  - 1.3.2
  - 1.3.1
  - 1.3
  - 1.2.2
  - 1.2.1
  - 1.2
  - 1.1.2
  - 1.1.1
  - 1.1
  - 1.0.3
  - 1.0.2
  - 1.0.1
  - 1

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - go: 1.3.3
    - go: 1.3.2
    - go: 1.3.1
    - go: 1.3
    - go: 1.2.2
    - go: 1.2.1
    - go: 1.2
    - go: 1.1.2
    - go: 1.1.1
    - go: 1.1
    - go: 1.0.3
    - go: 1.0.2
    - go: 1.0.1
    - go: 1
